--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/izebergozz/.cache/wallpapers/snow.jpg"

-- Special
background="#1c2543"
foreground="#dbdeeb"
cursor="#dbdeeb"

-- Colors
color0="#1c2543"
color1="#9897BA"
color2="#90A0CE"
color3="#ABB4D8"
color4="#ACBBE3"
color5="#BBC2DE"
color6="#B9C4E5"
color7="#dbdeeb"
color8="#999ba4"
color9="#9897BA"
color10="#90A0CE"
color11="#ABB4D8"
color12="#ACBBE3"
color13="#BBC2DE"
color14="#B9C4E5"
color15="#dbdeeb"
