# Shell variables
# Generated by 'wal'
wallpaper='/home/izebergozz/.cache/wallpapers/snow.jpg'

# Special
background='#1c2543'
foreground='#dbdeeb'
cursor='#dbdeeb'

# Colors
color0='#1c2543'
color1='#9897BA'
color2='#90A0CE'
color3='#ABB4D8'
color4='#ACBBE3'
color5='#BBC2DE'
color6='#B9C4E5'
color7='#dbdeeb'
color8='#999ba4'
color9='#9897BA'
color10='#90A0CE'
color11='#ABB4D8'
color12='#ACBBE3'
color13='#BBC2DE'
color14='#B9C4E5'
color15='#dbdeeb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
