--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/izebergozz/.cache/wallpapers/building.png"

-- Special
background="#0c0c0c"
foreground="#d8d8d5"
cursor="#d8d8d5"

-- Colors
color0="#0c0c0c"
color1="#8C5837"
color2="#956A50"
color3="#798181"
color4="#8F9C9D"
color5="#98A4A4"
color6="#B2B6B1"
color7="#d8d8d5"
color8="#979795"
color9="#8C5837"
color10="#956A50"
color11="#798181"
color12="#8F9C9D"
color13="#98A4A4"
color14="#B2B6B1"
color15="#d8d8d5"
